"""Site content shared by templates. Every user-facing string is bilingual: L(en, id)."""


def L(en, id_):
    return {"en": en, "id": id_}


# Public address of the site. Used for canonical links and link previews (WhatsApp, LinkedIn…).
# Change to "https://verbind-tech.net/" once the site moves to the company domain.
SITE_URL = "https://leon6geek.github.io/verbindtech/"

COMPANY = {
    "name": "Verbindtech Machinery",
    "wa": "6281932237600",
    "wa_display": "+62 819 3223 7600",
    "phone": "+622129566065",
    "phone_display": "(+62 21) 2956 6065",
    "email": "marketing@verbind-tech.net",
    "address": "Jalan Jababeka XVII Blok U-22 J No. 3, Harjamekar, Cikarang Utara, Kab. Bekasi, Jawa Barat 17530",
    "maps": "https://www.google.com/maps/search/?api=1&query=Verbindtech+Machinery+Jababeka+Cikarang",
    "maps_embed": "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3965.9603699341396!2d107.1327806!3d-6.2689425!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e698f4313f5eb2f%3A0x5e7cc68ceb6a2c82!2sVerbindtech%20Machinery!5e0!3m2!1sen!2sid!4v1588227491309!5m2!1sen!2sid",
    "instagram": "https://www.instagram.com/verbindtech_machinery",
    "linkedin": "https://www.linkedin.com/company/verbindtech-machinery/",
    "facebook": "https://www.facebook.com/TriMitraSuksesEngineering/",
}

EVENT = L("Meet us at ALLPACK Indonesia 2026 — Booth D104",
          "Kunjungi kami di ALLPACK Indonesia 2026 — Booth D104")

# ---------------------------------------------------------------- industries
INDUSTRIES = [
    {
        "slug": "pharmaceutical",
        "icon": "capsule",
        "img": "piping",
        "name": L("Pharmaceutical & Nutraceutical", "Farmasi & Nutrasetikal"),
        "short": L("Pharmaceutical", "Farmasi"),
        "teaser": L("Powder handling, filling and inspection designed with cGMP as the reference.",
                    "Penanganan serbuk, filling, dan inspeksi yang dirancang dengan acuan cGMP."),
        "headline": L("Process equipment that respects your validation work.",
                      "Peralatan proses yang menghormati kerja validasi Anda."),
        "intro": L("From a single sifter to a closed powder line, we design pharmaceutical equipment around hygiene, containment and accuracy — and we keep legacy European machines productive with retrofits.",
                   "Dari satu sifter hingga lini serbuk tertutup, kami merancang peralatan farmasi dengan fokus pada higienitas, containment, dan akurasi — serta menjaga mesin Eropa lama tetap produktif melalui retrofit."),
        "challenges": [
            (L("cGMP-ready design", "Desain siap cGMP"),
             L("Stainless contact parts, cleanable surfaces and layouts that support your GMP and documentation needs.",
               "Bagian kontak stainless, permukaan mudah dibersihkan, dan tata letak yang mendukung kebutuhan GMP serta dokumentasi Anda.")),
            (L("Dust and cross-contamination", "Debu & kontaminasi silang"),
             L("Closed transfer with vacuum conveying, IBCs and dust collection keeps powders contained between steps.",
               "Transfer tertutup dengan vacuum conveying, IBC, dan dust collector menjaga serbuk tetap terkendali antar tahap.")),
            (L("Dosing and fill accuracy", "Akurasi dosis & pengisian"),
             L("Auger, counting and liquid fillers matched to your product, verified with checkweighers and metal detection.",
               "Auger, counting, dan liquid filler yang disesuaikan dengan produk Anda, diverifikasi dengan checkweigher dan metal detector.")),
            (L("Ageing legacy machines", "Mesin lama yang menua"),
             L("Our team has retrofitted machines from brands such as Manesty, Bausch+Ströbel, Glatt and Diosna since 2012.",
               "Tim kami telah melakukan retrofit mesin merek Manesty, Bausch+Ströbel, Glatt, dan Diosna sejak 2012.")),
        ],
        "solutions": ["turnkey", "equipment", "spm", "services"],
        "machines": ["mixing", "sieving", "size", "conveying", "filling", "capping", "inspection"],
        "projects": ["tea-powder-line", "liquid-process", "hot-filling", "ampoule-feeder", "retrofit"],
        "clients": ["Kalbe", "Kimia Farma", "Bio Farma", "Novartis", "Darya-Varia", "Medifarma",
                    "Guardian Pharmatama", "Konimex", "Bintang Toedjoe"],
    },
    {
        "slug": "food-beverage",
        "icon": "leaf",
        "img": "line-cleanroom",
        "name": L("Food, Beverage & Dairy", "Makanan, Minuman & Susu"),
        "short": L("Food & beverage", "Makanan & minuman"),
        "teaser": L("Hygienic powder lines, packing for every bag style, and food-safety inspection.",
                    "Lini serbuk higienis, pengemasan untuk berbagai jenis kemasan, dan inspeksi keamanan pangan."),
        "headline": L("From raw ingredient to sealed pack — hygienically.",
                      "Dari bahan baku hingga kemasan tersegel — secara higienis."),
        "intro": L("Tea, coffee, sugar, milk powder, snacks or sauces: we combine mixing, sieving, conveying, packing and inspection into lines that protect your product and your brand.",
                   "Teh, kopi, gula, susu bubuk, camilan, atau saus: kami memadukan mixing, sieving, conveying, pengemasan, dan inspeksi menjadi lini yang melindungi produk dan merek Anda."),
        "challenges": [
            (L("Hygiene and food safety", "Higienitas & keamanan pangan"),
             L("Stainless construction, magnet traps and metal detectors keep foreign bodies out of your product.",
               "Konstruksi stainless, magnet trap, dan metal detector mencegah benda asing masuk ke produk Anda.")),
            (L("Many SKUs, many pack formats", "Banyak SKU & format kemasan"),
             L("Pillow, stick, gusseted, 3- and 4-side seal, doypack, tea bag and stand-up pouch — one partner for all formats.",
               "Pillow, stick, gusset, seal 3 & 4 sisi, doypack, kantong teh, hingga stand-up pouch — satu mitra untuk semua format.")),
            (L("Fragile and sticky products", "Produk rapuh & lengket"),
             L("Weighing systems for fragile snacks and ultrasonic screens for powders that clump or carry static.",
               "Sistem penimbangan untuk camilan rapuh dan ayakan ultrasonik untuk serbuk yang menggumpal atau bermuatan statis.")),
            (L("Packaging that sells", "Kemasan yang menjual"),
             L("Neat seals, accurate fills and clean labels — because the pack is also part of your promotion.",
               "Seal rapi, pengisian akurat, dan label bersih — karena kemasan juga bagian dari promosi Anda.")),
        ],
        "solutions": ["turnkey", "equipment", "services"],
        "machines": ["mixing", "sieving", "conveying", "filling", "packaging", "inspection"],
        "projects": ["tea-powder-line", "liquid-process"],
        "clients": ["Nutrifood", "Kerry", "Perfetti Van Melle", "Sukanda Djaya", "Aliet Green", "Great Giant Livestock"],
    },
    {
        "slug": "fmcg-personal-care",
        "icon": "bottle",
        "img": "spm-hot-filling",
        "name": L("FMCG & Personal Care", "FMCG & Perawatan Diri"),
        "short": L("FMCG & personal care", "FMCG & perawatan diri"),
        "teaser": L("Filling, capping, labeling and end-of-line automation for high-volume brands.",
                    "Filling, capping, labeling, dan otomasi akhir lini untuk merek bervolume tinggi."),
        "headline": L("Keep high-volume lines fast, clean and consistent.",
                      "Jaga lini bervolume tinggi tetap cepat, bersih, dan konsisten."),
        "intro": L("Bottles, jars, tubes and sachets — we supply and integrate filling, sealing, capping and labeling, and build special machines for the steps standard equipment does not cover.",
                   "Botol, jar, tube, dan sachet — kami memasok dan mengintegrasikan filling, sealing, capping, dan labeling, serta membangun mesin khusus untuk tahap yang tidak tercakup mesin standar."),
        "challenges": [
            (L("Speed and changeover", "Kecepatan & pergantian produk"),
             L("Lines that switch between products and bottle sizes without long stops.",
               "Lini yang dapat berganti produk dan ukuran botol tanpa henti lama.")),
            (L("Container cleanliness", "Kebersihan wadah"),
             L("Automatic blow-and-suction cleaning removes dust and static from plastic bottles before filling.",
               "Pembersihan blow-and-suction otomatis menghilangkan debu dan muatan statis dari botol plastik sebelum pengisian.")),
            (L("End-of-line labour", "Tenaga kerja akhir lini"),
             L("Case packers and top loaders designed to fit the space you already have.",
               "Case packer dan top loader yang dirancang sesuai ruang yang sudah Anda miliki.")),
            (L("Presentation on shelf", "Tampilan di rak"),
             L("Precise labeling, induction sealing and capping for a pack that looks right every time.",
               "Labeling presisi, induction sealing, dan capping agar kemasan selalu tampil sempurna.")),
        ],
        "solutions": ["spm", "equipment", "services"],
        "machines": ["filling", "capping", "packaging", "inspection"],
        "projects": ["case-packer", "blow-suct", "hot-filling", "liquid-process"],
        "clients": ["Procter & Gamble", "L'Oréal", "Bintang Toedjoe", "Nutrifood"],
    },
    {
        "slug": "chemical-agro",
        "icon": "flask",
        "img": "shop-18-67",
        "name": L("Chemical & Agro", "Kimia & Agro"),
        "short": L("Chemical & agro", "Kimia & agro"),
        "teaser": L("Filling units, big-bag packing, sealing and stainless tanks for chemical producers.",
                    "Unit filling, pengemasan big bag, sealing, dan tangki stainless untuk produsen kimia."),
        "headline": L("Safe, sealed handling for chemicals and agro-inputs.",
                      "Penanganan aman dan tersegel untuk bahan kimia dan input pertanian."),
        "intro": L("Pesticides, fertilisers, lubricants and specialty chemicals need accurate filling, leak-proof sealing and robust construction. We build and supply equipment for exactly that.",
                   "Pestisida, pupuk, pelumas, dan bahan kimia khusus membutuhkan pengisian akurat, seal anti-bocor, dan konstruksi kokoh. Untuk itulah kami membangun dan memasok peralatan."),
        "challenges": [
            (L("Leak-proof packs", "Kemasan anti-bocor"),
             L("Induction foil sealing and capping that keep liquids in and contamination out.",
               "Induction foil sealing dan capping yang menjaga cairan tetap di dalam dan kontaminasi di luar.")),
            (L("Accurate filling", "Pengisian akurat"),
             L("Liquid and powder fillers sized for your containers, from bottles to big bags.",
               "Filler cair dan serbuk sesuai wadah Anda, dari botol hingga big bag.")),
            (L("Dust and operator safety", "Debu & keselamatan operator"),
             L("Bottom-up big-bag filling and closed transfer to reduce dust at the packing station.",
               "Pengisian big bag bottom-up dan transfer tertutup untuk mengurangi debu di stasiun pengemasan.")),
            (L("Robust construction", "Konstruksi kokoh"),
             L("Stainless and non-stainless fabrication from our Jababeka plant, suited to harsh duty.",
               "Fabrikasi stainless dan non-stainless dari pabrik kami di Jababeka, sesuai untuk kondisi berat.")),
        ],
        "solutions": ["equipment", "fabrication", "services"],
        "machines": ["filling", "packaging", "capping", "mixing"],
        "projects": ["liquid-process"],
        "clients": ["CBA Chemical", "Pupuk Kaltim"],
    },
    {
        "slug": "automotive-industrial",
        "icon": "gear",
        "img": "spm-render",
        "name": L("Automotive & Industrial", "Otomotif & Industri"),
        "short": L("Automotive & industrial", "Otomotif & industri"),
        "teaser": L("Special purpose machines, jigs, inspection and quick die change for component makers.",
                    "Mesin khusus, jig, inspeksi, dan quick die change untuk produsen komponen."),
        "headline": L("Special machines built around your part and your cycle time.",
                      "Mesin khusus yang dibangun sesuai part dan cycle time Anda."),
        "intro": L("We have supported automotive and heavy industry since 2008 — designing inspection stations, assembly jigs, press feeders and material handling with lean manufacturing as the reference.",
                   "Kami mendukung industri otomotif dan berat sejak 2008 — merancang stasiun inspeksi, jig perakitan, press feeder, dan material handling dengan lean manufacturing sebagai acuan."),
        "challenges": [
            (L("Cycle time", "Cycle time"),
             L("Automation designed to the takt of your line, not the other way round.",
               "Otomasi yang dirancang mengikuti takt lini Anda, bukan sebaliknya.")),
            (L("Zero-defect quality", "Kualitas tanpa cacat"),
             L("Dedicated inspection stations — such as inner-tube scratch inspection — catch defects before parts move on.",
               "Stasiun inspeksi khusus — seperti inspeksi goresan inner tube — menangkap cacat sebelum part berpindah proses.")),
            (L("Fast changeover (Dandori)", "Pergantian cepat (Dandori)"),
             L("Multi-alignment die-change systems that shorten press changeovers.",
               "Sistem penggantian die multi-alignment yang mempersingkat waktu pergantian press.")),
            (L("Lean, energy-free handling", "Handling lean tanpa energi"),
             L("Mechanically driven conveyors and jigs that remove waste without adding power consumption.",
               "Konveyor dan jig bertenaga mekanis yang menghilangkan pemborosan tanpa menambah konsumsi listrik.")),
        ],
        "solutions": ["spm", "fabrication", "services"],
        "machines": ["inspection"],
        "projects": ["dandori", "powerless-conveyor", "steering-shaft", "assembly-jigs"],
        "clients": ["AISIN (Toyota Group)", "KYB", "Kohler", "Keramischer Ofenbau", "Vakumix", "Prosweal Indomax", "Vadco Prosper Mega"],
    },
]
INDUSTRY = {i["slug"]: i for i in INDUSTRIES}

# ---------------------------------------------------------------- solutions
SOLUTIONS = [
    {
        "key": "turnkey", "anchor": "turnkey-lines", "img": "line-cleanroom", "icon": "line",
        "name": L("Turnkey process lines", "Lini proses turnkey"),
        "teaser": L("Design, manufacture, installation and commissioning of complete lines — one accountable partner.",
                    "Desain, manufaktur, instalasi, dan commissioning lini lengkap — satu mitra yang bertanggung jawab."),
    },
    {
        "key": "spm", "anchor": "special-purpose-machines", "img": "spm-render", "icon": "robot",
        "name": L("Special purpose machines", "Mesin khusus (SPM)"),
        "teaser": L("Custom automation, inspection and assembly machines designed from your requirement.",
                    "Mesin otomasi, inspeksi, dan perakitan khusus yang dirancang dari kebutuhan Anda."),
    },
    {
        "key": "equipment", "anchor": "equipment", "img": "insp-combo", "icon": "box",
        "name": L("Process & packaging equipment", "Peralatan proses & pengemasan"),
        "teaser": L("80+ proven standard machines from our technology partners, integrated locally.",
                    "80+ mesin standar teruji dari mitra teknologi kami, diintegrasikan secara lokal."),
    },
    {
        "key": "fabrication", "anchor": "fabrication", "img": "tank-delivery", "icon": "weld",
        "name": L("Fabrication & precision parts", "Fabrikasi & part presisi"),
        "teaser": L("Stainless and non-stainless fabrication, GMP tanks, jigs and spare parts from Jababeka.",
                    "Fabrikasi stainless dan non-stainless, tangki GMP, jig, dan spare part dari Jababeka."),
    },
    {
        "key": "services", "anchor": "", "img": "checkweigher-site", "icon": "wrench",
        "name": L("Service & retrofit", "Layanan & retrofit"),
        "teaser": L("Installation, maintenance, breakdown support and upgrades for the whole machine lifecycle.",
                    "Instalasi, perawatan, penanganan kerusakan, dan upgrade sepanjang siklus hidup mesin."),
    },
]
SOLUTION = {s["key"]: s for s in SOLUTIONS}

# ---------------------------------------------------------------- services
SERVICES = [
    {"icon": "install", "anchor": "installation",
     "name": L("Installation & commissioning", "Instalasi & commissioning"),
     "desc": L("We install, start up and commission on your site, and test machines with you before handover.",
               "Kami memasang, menjalankan, dan melakukan commissioning di lokasi Anda, serta menguji mesin bersama Anda sebelum serah terima.")},
    {"icon": "calendar", "anchor": "maintenance",
     "name": L("Preventive & predictive maintenance", "Perawatan preventif & prediktif"),
     "desc": L("Planned maintenance based on TPM practice, with parts replaced before they fail — not after.",
               "Perawatan terencana berbasis praktik TPM, dengan penggantian part sebelum rusak — bukan sesudahnya.")},
    {"icon": "bolt", "anchor": "breakdown",
     "name": L("Corrective maintenance", "Perawatan korektif"),
     "desc": L("A fast-response team for breakdowns, backed by the engineers who designed the machine.",
               "Tim respons cepat untuk kerusakan, didukung oleh engineer yang merancang mesin tersebut.")},
    {"icon": "refresh", "anchor": "retrofit",
     "name": L("Retrofit & upgrade", "Retrofit & upgrade"),
     "desc": L("New controls, drives and modifications that extend the life and output of existing machines.",
               "Kontrol, penggerak, dan modifikasi baru yang memperpanjang umur dan output mesin yang ada.")},
    {"icon": "parts", "anchor": "spare-parts",
     "name": L("Spare parts & fabricated parts", "Spare part & part fabrikasi"),
     "desc": L("Partner spare parts plus locally machined and fabricated parts when originals are slow or unavailable.",
               "Spare part dari mitra serta part hasil machining dan fabrikasi lokal saat part asli lama atau tidak tersedia.")},
    {"icon": "building", "anchor": "facility",
     "name": L("Building facility maintenance", "Perawatan fasilitas gedung"),
     "desc": L("Support for the utilities and facilities around your production area.",
               "Dukungan untuk utilitas dan fasilitas di sekitar area produksi Anda.")},
]

# ---------------------------------------------------------------- projects
PROJECTS = [
    {
        "slug": "tea-powder-line", "industries": ["food-beverage", "pharmaceutical"], "featured": True,
        "img": "line-cleanroom", "gallery": ["line-render", "line-cleanroom", "line-fillers"],
        "type": L("Turnkey process line", "Lini proses turnkey"),
        "title": L("Tea powder processing line", "Lini pengolahan teh bubuk"),
        "challenge": L("A hygienic, closed powder process from raw-material dumping all the way to filling — designed to cGMP.",
                       "Proses serbuk yang higienis dan tertutup dari penuangan bahan baku hingga pengisian — dirancang sesuai cGMP."),
        "solution": L("We designed, manufactured, installed and commissioned the complete line: dumping station, vibro screen, ribbon mixer, vacuum conveying, magnet trap, metal detector, IBC and a three-outlet auger feeding the filling machines.",
                      "Kami merancang, memproduksi, memasang, dan melakukan commissioning seluruh lini: dumping station, vibro screen, ribbon mixer, vacuum conveying, magnet trap, metal detector, IBC, dan auger tiga outlet yang menyuplai mesin filling."),
        "result": L("One accountable supplier from 3D model to commissioning, and a closed-loop system that keeps product contained.",
                    "Satu pemasok yang bertanggung jawab dari model 3D hingga commissioning, dan sistem closed-loop yang menjaga produk tetap tertutup."),
        "scope": [L("3D design", "Desain 3D"), L("Manufacture", "Manufaktur"), L("Installation", "Instalasi"), L("Commissioning", "Commissioning"), L("cGMP", "cGMP")],
    },
    {
        "slug": "liquid-process", "industries": ["pharmaceutical", "fmcg-personal-care", "food-beverage", "chemical-agro"], "featured": False,
        "img": "liquid-plant-render", "gallery": ["liquid-plant-render", "piping", "tank-delivery", "tanks"],
        "type": L("Process system", "Sistem proses"),
        "title": L("Stainless liquid process system", "Sistem proses cair stainless"),
        "challenge": L("Mixing tanks, filtration and transfer piping that work as one system, not a collection of separate pieces.",
                       "Tangki mixing, filtrasi, dan pipa transfer yang bekerja sebagai satu sistem, bukan kumpulan bagian terpisah."),
        "solution": L("A 3D plant layout followed by stainless tanks, piping and skids, delivered and installed on site by our team.",
                      "Layout pabrik 3D, dilanjutkan dengan tangki stainless, perpipaan, dan skid yang dikirim serta dipasang di lokasi oleh tim kami."),
        "result": L("A complete liquid area — from design model to installed tanks — handled by one team.",
                    "Area proses cair yang lengkap — dari model desain hingga tangki terpasang — ditangani oleh satu tim."),
        "scope": [L("Plant layout", "Layout pabrik"), L("Stainless tanks", "Tangki stainless"), L("Piping", "Perpipaan"), L("Installation", "Instalasi")],
    },
    {
        "slug": "case-packer", "industries": ["fmcg-personal-care"], "featured": True,
        "img": "spm-case-packer", "gallery": ["spm-case-packer"],
        "type": L("Special purpose machine", "Mesin khusus"),
        "title": L("Case packer with automatic top loader", "Case packer dengan top loader otomatis"),
        "challenge": L("Automate packing of a liquid soap product into cases — within the floor space the customer already had.",
                       "Mengotomasi pengemasan produk sabun cair ke dalam karton — di dalam ruang yang sudah dimiliki pelanggan."),
        "solution": L("A case packer with an automatic top loader, specially designed around the available layout.",
                      "Case packer dengan top loader otomatis yang dirancang khusus mengikuti layout yang tersedia."),
        "result": L("End-of-line packing automated without rebuilding the line around it.",
                    "Pengemasan akhir lini teroptimasi tanpa harus membangun ulang lini di sekitarnya."),
        "scope": [L("Concept & 3D", "Konsep & 3D"), L("Build", "Pembuatan"), L("Installation", "Instalasi")],
    },
    {
        "slug": "dandori", "industries": ["automotive-industrial"], "featured": True,
        "img": "spm-dandori", "gallery": ["spm-dandori"],
        "type": L("Special purpose machine", "Mesin khusus"),
        "title": L("Dandori multi-alignment press auto feeder", "Auto feeder press Dandori multi-alignment"),
        "challenge": L("Shorten die changeovers on a press line handling five dies.",
                       "Mempersingkat pergantian die pada lini press yang menangani lima die."),
        "solution": L("An 11.3 m die-change system with roller carts for five dies, a preparation station, and movable and fixed transfer units in automatic and manual modes.",
                      "Sistem penggantian die sepanjang 11,3 m dengan roller cart untuk lima die, stasiun persiapan, serta unit transfer bergerak dan tetap dalam mode otomatis dan manual."),
        "result": L("Dies are prepared off-line and transferred into the press in alignment, ready for the next run.",
                    "Die disiapkan di luar lini dan ditransfer ke press dalam posisi sejajar, siap untuk produksi berikutnya."),
        "scope": [L("Layout design", "Desain layout"), L("Build", "Pembuatan"), L("Automation", "Otomasi")],
    },
    {
        "slug": "hot-filling", "industries": ["pharmaceutical", "fmcg-personal-care"], "featured": False,
        "img": "spm-hot-filling", "gallery": ["spm-hot-filling"],
        "type": L("Special purpose machine", "Mesin khusus"),
        "title": L("Hot filling & cooling unit", "Unit hot filling & pendinginan"),
        "challenge": L("Fill a medical product hot, then cool it slowly and consistently.",
                       "Mengisi produk medis dalam kondisi panas, lalu mendinginkannya secara perlahan dan konsisten."),
        "solution": L("A hot filling machine combined with a controlled, slow cooling process.",
                      "Mesin hot filling yang dipadukan dengan proses pendinginan perlahan yang terkendali."),
        "result": L("Filling and cooling handled in one continuous unit.",
                    "Pengisian dan pendinginan ditangani dalam satu unit yang berkesinambungan."),
        "scope": [L("Design", "Desain"), L("Build", "Pembuatan"), L("Commissioning", "Commissioning")],
    },
    {
        "slug": "powerless-conveyor", "industries": ["automotive-industrial"], "featured": False,
        "img": "spm-powerless", "gallery": ["spm-powerless"],
        "type": L("Special purpose machine", "Mesin khusus"),
        "title": L("Powerless scrap conveyor", "Konveyor scrap tanpa listrik"),
        "challenge": L("Move scrap to the scrap box continuously — without adding motors or energy use.",
                       "Memindahkan scrap ke kotak scrap secara kontinu — tanpa menambah motor atau konsumsi energi."),
        "solution": L("A straight and a lifting conveyor driven mechanically by a push-and-pull arm through a linear gear, bevel gear unit and universal joint.",
                      "Konveyor lurus dan konveyor angkat yang digerakkan secara mekanis oleh lengan push-pull melalui linear gear, bevel gear unit, dan universal joint."),
        "result": L("Continuous scrap handling with zero added electrical power.",
                    "Penanganan scrap yang kontinu tanpa tambahan daya listrik."),
        "scope": [L("Mechanical design", "Desain mekanis"), L("Build", "Pembuatan")],
    },
    {
        "slug": "blow-suct", "industries": ["fmcg-personal-care"], "featured": False,
        "img": "spm-blow-suct", "gallery": ["spm-blow-suct"],
        "type": L("Special purpose machine", "Mesin khusus"),
        "title": L("Blow & suction bottle cleaner", "Pembersih botol blow & suction"),
        "challenge": L("Plastic bottles arrive with dust and static charge that affect filling and appearance.",
                       "Botol plastik datang dengan debu dan muatan statis yang mengganggu pengisian dan tampilan."),
        "solution": L("Automatic blow-and-suction cleaning that removes dust and the electrostatic effect before filling.",
                      "Pembersihan blow-and-suction otomatis yang menghilangkan debu dan efek elektrostatis sebelum pengisian."),
        "result": L("Clean containers enter the filler, every bottle, every shift.",
                    "Wadah bersih masuk ke filler — setiap botol, setiap shift."),
        "scope": [L("Design", "Desain"), L("Build", "Pembuatan")],
    },
    {
        "slug": "ampoule-feeder", "industries": ["pharmaceutical"], "featured": False,
        "img": "spm-ampoule", "gallery": ["spm-ampoule"],
        "type": L("Special purpose machine", "Mesin khusus"),
        "title": L("Ampoule feeder for blister machine", "Ampoule feeder untuk mesin blister"),
        "challenge": L("Feed ampoules reliably into a blister packing machine.",
                       "Menyuplai ampul secara andal ke mesin blister packing."),
        "solution": L("A dedicated ampoule feeder matched to the blister machine.",
                      "Ampoule feeder khusus yang disesuaikan dengan mesin blister."),
        "result": L("Steady infeed for the blister line.",
                    "Infeed yang stabil untuk lini blister."),
        "scope": [L("Design", "Desain"), L("Build", "Pembuatan")],
    },
    {
        "slug": "steering-shaft", "industries": ["automotive-industrial"], "featured": False,
        "img": "spm-steering", "gallery": ["spm-steering"],
        "type": L("Special purpose machine", "Mesin khusus"),
        "title": L("Steering shaft station", "Stasiun steering shaft"),
        "challenge": L("A dedicated process station for steering shaft production.",
                       "Stasiun proses khusus untuk produksi steering shaft."),
        "solution": L("A purpose-built station with fixturing and guided motion for the shaft.",
                      "Stasiun khusus dengan fixture dan gerakan terpandu untuk shaft."),
        "result": L("Repeatable processing for a safety-critical part.",
                    "Proses yang konsisten untuk part yang kritikal terhadap keselamatan."),
        "scope": [L("Design", "Desain"), L("Build", "Pembuatan")],
    },
    {
        "slug": "assembly-jigs", "industries": ["automotive-industrial"], "featured": False,
        "img": "auto-jig-1", "gallery": ["auto-jig-1", "auto-jig-3", "auto-jig-2", "auto-station", "auto-hydraulic"],
        "type": L("Jigs & stations", "Jig & stasiun"),
        "title": L("Pneumatic assembly jigs & stations", "Jig & stasiun perakitan pneumatik"),
        "challenge": L("Hold and position automotive components precisely during assembly.",
                       "Menahan dan memposisikan komponen otomotif secara presisi saat perakitan."),
        "solution": L("Pneumatic clamping jigs, guarded stations and a mobile pump unit, built in-house.",
                      "Jig clamping pneumatik, stasiun berpengaman, dan unit pompa bergerak yang dibuat sendiri."),
        "result": L("Consistent positioning and safer operation at every station.",
                    "Posisi yang konsisten dan operasi lebih aman di setiap stasiun."),
        "scope": [L("Design", "Desain"), L("Fabrication", "Fabrikasi"), L("Pneumatics", "Pneumatik")],
    },
    {
        "slug": "retrofit", "industries": ["pharmaceutical", "food-beverage"], "featured": False,
        "img": "team", "gallery": ["team"],
        "type": L("Retrofit", "Retrofit"),
        "title": L("Retrofits of European process machines", "Retrofit mesin proses Eropa"),
        "challenge": L("Keep proven pharma and food machines productive when original support is far away.",
                       "Menjaga mesin farmasi dan pangan yang sudah teruji tetap produktif ketika dukungan pabrikan aslinya jauh."),
        "solution": L("Since 2012 our team has modified and retrofitted machines from brands such as Manesty, Bausch+Ströbel, Glatt and Diosna.",
                      "Sejak 2012 tim kami telah memodifikasi dan melakukan retrofit mesin merek Manesty, Bausch+Ströbel, Glatt, dan Diosna."),
        "result": L("Longer machine life and local support for imported equipment.",
                    "Umur mesin lebih panjang dan dukungan lokal untuk peralatan impor."),
        "scope": [L("Assessment", "Asesmen"), L("Modification", "Modifikasi"), L("Commissioning", "Commissioning")],
    },
]
PROJECT = {p["slug"]: p for p in PROJECTS}

# ---------------------------------------------------------------- clients & partners
CLIENTS = [
    "Kalbe", "Kimia Farma", "Bio Farma", "Novartis", "Procter & Gamble", "L'Oréal", "AISIN", "KYB",
    "Kerry", "Nutrifood", "Darya-Varia", "Medifarma", "Konimex", "Kohler", "Perfetti Van Melle",
    "Bintang Toedjoe", "Guardian Pharmatama", "Sukanda Djaya", "Pupuk Kaltim", "CBA Chemical",
    "Aliet Green", "Great Giant Livestock", "Vadco Prosper Mega", "Keramischer Ofenbau", "Vakumix", "Prosweal Indomax",
]
CLIENT_STRIP = ["Kalbe", "Kimia Farma", "Bio Farma", "Novartis", "P&G", "L'Oréal", "AISIN", "KYB", "Kerry", "Nutrifood", "Kohler"]

PARTNERS = [
    ("Xinxiang Chenwei Machinery", L("Mixing, milling, sieving & conveying", "Mixing, milling, sieving & conveying")),
    ("Elin Packaging Machinery", L("Processing & packaging equipment", "Peralatan proses & pengemasan")),
    ("Spack Machine", L("Form-fill-seal & filling", "Form-fill-seal & filling")),
    ("Zegoo Instrument (Shanghai)", L("Metal detection & checkweighing", "Metal detector & checkweigher")),
    ("Shanghai Shengsen", L("Packaging equipment", "Peralatan pengemasan")),
    ("Mitra Cipta Teknika", L("Fabrication & installation", "Fabrikasi & instalasi")),
]

# ---------------------------------------------------------------- process & proof
STEPS = [
    (L("Requirement workshop", "Workshop kebutuhan"),
     L("We gather every requirement — product, output, space, utilities, standards — before proposing a machine.",
       "Kami mengumpulkan semua kebutuhan — produk, output, ruang, utilitas, standar — sebelum mengusulkan mesin."),
     L("Gathering all ideas", "Gathering all ideas")),
    (L("Concept & 3D model", "Konsep & model 3D"),
     L("Your requirement becomes a 3D model and layout you can review with your team.",
       "Kebutuhan Anda diwujudkan menjadi model 3D dan layout yang dapat Anda tinjau bersama tim."),
     L("Building prototype", "Building prototype")),
    (L("Proposal & design review", "Proposal & tinjauan desain"),
     L("We recheck the design against proven practice and freeze an approved drawing with you.",
       "Kami memeriksa ulang desain terhadap praktik yang teruji dan menetapkan gambar yang disetujui bersama Anda."),
     L("Customer-based survey", "Customer-based survey")),
    (L("Build or source", "Produksi atau pengadaan"),
     L("Custom machines are built and assembled in Indonesia; standard machines come from our partner network.",
       "Mesin khusus dibuat dan dirakit di Indonesia; mesin standar berasal dari jaringan mitra kami."),
     L("Production", "Production")),
    (L("Test run with you", "Uji coba bersama Anda"),
     L("Every machine is checked and test-run at our Cikarang workshop with you before it ships.",
       "Setiap mesin diperiksa dan diuji di workshop Cikarang bersama Anda sebelum dikirim."),
     L("Quality control", "Quality control")),
    (L("Install, commission & support", "Instalasi, commissioning & dukungan"),
     L("We install and commission on site, then stay on for after-sales service and spare parts.",
       "Kami memasang dan melakukan commissioning di lokasi, lalu tetap mendampingi dengan layanan purna jual dan spare part."),
     L("After-sales service", "After-sales service")),
]

CHECKLIST = [
    (L("Is the supplier experienced with your process?", "Apakah pemasok berpengalaman dengan proses Anda?"),
     L("A supplier who understands the whole flow — raw material to finished pack — can tell you up front whether a machine will really deliver your shape, size and quality.",
       "Pemasok yang memahami alur dari bahan baku hingga kemasan jadi dapat memberi tahu sejak awal apakah mesin benar-benar menghasilkan bentuk, ukuran, dan kualitas yang Anda inginkan."),
     L("Since 2008 across pharma, food, FMCG, chemical and automotive.", "Sejak 2008 di farmasi, pangan, FMCG, kimia, dan otomotif.")),
    (L("Will spare parts be there when you need them?", "Apakah spare part tersedia saat dibutuhkan?"),
     L("Parts should be replaced before they fail, according to their service life — which means they must be available locally.",
       "Part sebaiknya diganti sebelum rusak sesuai umur pakainya — artinya part harus tersedia secara lokal."),
     L("Partner parts plus local machining and fabrication in Jababeka.", "Part dari mitra ditambah machining dan fabrikasi lokal di Jababeka.")),
    (L("Do you know the full specification?", "Apakah Anda memahami spesifikasi lengkapnya?"),
     L("Dimensions, power, space, speed, materials and the whole process must be clear before you buy — not when the machine arrives.",
       "Dimensi, daya listrik, ruang, kecepatan, material, dan seluruh proses harus jelas sebelum membeli — bukan saat mesin tiba."),
     L("Requirement workshop, 3D model and approved drawing before production.", "Workshop kebutuhan, model 3D, dan gambar yang disetujui sebelum produksi.")),
    (L("Has the machine been tested?", "Apakah mesin sudah diuji?"),
     L("Insist on seeing the machine run with your product before it is shipped to your plant.",
       "Pastikan Anda melihat mesin berjalan dengan produk Anda sebelum dikirim ke pabrik."),
     L("Test run with you at our Cikarang workshop before delivery.", "Uji coba bersama Anda di workshop Cikarang sebelum pengiriman.")),
    (L("What does the warranty really cover?", "Apa yang benar-benar dicakup garansi?"),
     L("No machine is perfect. A warranty backed by a team that knows the machine is what protects your production.",
       "Tidak ada mesin yang sempurna. Garansi yang didukung tim yang memahami mesin itulah yang melindungi produksi Anda."),
     L("1-year mechanical & electrical warranty on machines we build.", "Garansi mekanis & elektrikal 1 tahun untuk mesin buatan kami.")),
]

TIMELINE = [
    ("2008", L("Trimitra Jaya Mandiri", "Trimitra Jaya Mandiri"),
     L("The group starts supporting general items and special purpose machines, first for the automotive industry.",
       "Grup mulai mendukung general item dan mesin khusus, pertama kali untuk industri otomotif.")),
    ("2010", L("Trimitra Engineering Perkasa", "Trimitra Engineering Perkasa"),
     L("Demand for precision parts gives rise to TEP, supporting spare-part makers, jigs and heavy industry.",
       "Permintaan part presisi melahirkan TEP, yang mendukung pembuat spare part, jig, dan industri berat.")),
    ("2012", L("MCT & TWU", "MCT & TWU"),
     L("Mitra Cipta Teknika starts fabrication and installation, beginning with a pharmaceutical powder process. TWU retrofits pharma and food machines.",
       "Mitra Cipta Teknika memulai fabrikasi dan instalasi, diawali proses serbuk farmasi. TWU melakukan retrofit mesin farmasi dan pangan.")),
    ("2014", L("Automotive SPM", "SPM otomotif"),
     L("TWU focuses on special purpose machines for the automotive industry.",
       "TWU berfokus pada mesin khusus untuk industri otomotif.")),
    ("2016", L("Tanks, systems & AGRU", "Tangki, sistem & AGRU"),
     L("MCT adds tank and system fabrication at a new plant in Setu; AGRU builds special machines for pharma and FMCG.",
       "MCT menambah fabrikasi tangki dan sistem di pabrik baru di Setu; AGRU membangun mesin khusus untuk farmasi dan FMCG.")),
    ("2019", L("Jababeka plant", "Pabrik Jababeka"),
     L("A new plant in Jababeka, Cikarang, for stainless and non-stainless steel fabrication.",
       "Pabrik baru di Jababeka, Cikarang, untuk fabrikasi baja stainless dan non-stainless.")),
    ("2020", L("Verbindtech Machinery", "Verbindtech Machinery"),
     L("Established for standard machines and trading, with designs standardised toward Industry 4.0.",
       "Didirikan untuk mesin standar dan perdagangan, dengan desain yang distandarkan menuju Industri 4.0.")),
]

VALUES = [
    (L("Quality", "Kualitas"),
     L("The highest standards for our services, products and project management — and a commitment to excellence at all times.",
       "Standar tertinggi untuk layanan, produk, dan manajemen proyek kami — serta komitmen pada keunggulan setiap saat.")),
    (L("Commitment", "Komitmen"),
     L("Reliability and long-term relationships with clients and partners in everything we do.",
       "Keandalan dan hubungan jangka panjang dengan klien dan mitra dalam semua yang kami lakukan.")),
    (L("Trust", "Kepercayaan"),
     L("We put clients first, protect your interests and stand by our reputation.",
       "Kami mengutamakan klien, melindungi kepentingan Anda, dan menjaga reputasi kami.")),
]

COVERAGE = ["Jakarta", "Bekasi", "Cikarang", "Karawang", "Bandung", "Cirebon", "Semarang", "Yogyakarta", "Surabaya"]

FAQ = [
    (L("How long does a machine take?", "Berapa lama waktu pembuatan mesin?"),
     L("Custom machines typically take 1–2 months of production after the drawing is approved. Lead times for standard machines depend on the model and are confirmed in our quotation.",
       "Mesin khusus umumnya membutuhkan 1–2 bulan produksi setelah gambar disetujui. Waktu pengiriman mesin standar bergantung pada model dan dikonfirmasi dalam penawaran kami.")),
    (L("Can we see the machine before delivery?", "Bisakah kami melihat mesin sebelum dikirim?"),
     L("Yes. We reassemble and test-run every machine at our Cikarang workshop together with you, and adjust settings until it performs as ordered.",
       "Ya. Kami merakit ulang dan menguji setiap mesin di workshop Cikarang bersama Anda, dan menyesuaikan setelan hingga sesuai pesanan.")),
    (L("What warranty do you give?", "Garansi apa yang diberikan?"),
     L("Machines we build carry a 1-year warranty on mechanical and electrical parts. For certain machines we include up to three after-sales visits.",
       "Mesin buatan kami bergaransi 1 tahun untuk bagian mekanis dan elektrikal. Untuk mesin tertentu kami menyertakan hingga tiga kunjungan purna jual.")),
    (L("Which areas do you serve?", "Wilayah mana yang dilayani?"),
     L("We are based in Jababeka, Cikarang and serve Jabodetabek, West, Central and East Java and Yogyakarta, with clients also in Sumatra and Kalimantan.",
       "Kami berbasis di Jababeka, Cikarang dan melayani Jabodetabek, Jawa Barat, Jawa Tengah, Jawa Timur, dan Yogyakarta, dengan klien juga di Sumatra dan Kalimantan.")),
    (L("Standard machine or custom build?", "Mesin standar atau buatan khusus?"),
     L("Both. Standard machines come from our technology partners; customised machines are designed, built and assembled in Indonesia. We will recommend what fits your process and budget.",
       "Keduanya. Mesin standar berasal dari mitra teknologi kami; mesin khusus dirancang, dibuat, dan dirakit di Indonesia. Kami akan merekomendasikan yang sesuai proses dan anggaran Anda.")),
    (L("What should we send for a quotation?", "Apa yang perlu dikirim untuk penawaran?"),
     L("Your product, target output, container or pack format and available space. A URS, drawing or photos of your current line help us respond faster.",
       "Produk, target output, format wadah atau kemasan, dan ruang yang tersedia. URS, gambar, atau foto lini Anda saat ini membantu kami merespons lebih cepat.")),
]

CATEGORIES = [
    ("mixing", L("Mixing", "Mixing"), L("Ribbon, V, W, 3D and cone mixers", "Mixer ribbon, V, W, 3D, dan cone")),
    ("size", L("Milling & crushing", "Milling & crushing"), L("Pulse, pin, cryogenic and ultra-fine mills", "Mesin giling pulse, pin, kriogenik, dan ultra-halus")),
    ("sieving", L("Sieving & screening", "Sieving & screening"), L("Vibrating, ultrasonic and centrifugal sifters", "Ayakan getar, ultrasonik, dan sentrifugal")),
    ("conveying", L("Conveying & feeding", "Conveying & feeding"), L("Vacuum, screw, spring and vibratory feeders", "Feeder vakum, screw, spring, dan vibrasi")),
    ("filling", L("Filling", "Filling"), L("Auger, powder, liquid, capsule and vial filling", "Filling auger, serbuk, cair, kapsul, dan vial")),
    ("packaging", L("Packaging", "Pengemasan"), L("VFFS, sachet, doypack, tea bag, flow wrap, big bag", "VFFS, sachet, doypack, kantong teh, flow wrap, big bag")),
    ("capping", L("Sealing, capping & labeling", "Sealing, capping & labeling"), L("Induction sealing, cappers, labelers, bottle washers", "Induction sealing, capper, labeler, pencuci botol")),
    ("inspection", L("Inspection & weighing", "Inspeksi & penimbangan"), L("Metal detectors, checkweighers, sorters, scales", "Metal detector, checkweigher, sorter, timbangan")),
]
